/**
 * app.js
 * Orchestrates the full 4-agent research pipeline.
 */

import { runPlanner }    from './agents/planner.js';
import { runResearcher } from './agents/researcher.js';
import { runWriter }     from './agents/writer.js';
import { runReviewer }   from './agents/reviewer.js';
import {
  resetAllAgents,
  showFinalReport,
  hideFinalReport,
  showToast,
  setLaunchButton
} from './utils/ui.js';

// ─── API Key Management ──────────────────────────────────────────────────────

function getApiKey() {
  return localStorage.getItem('gemini_api_key') || '';
}

function saveApiKey(key) {
  localStorage.setItem('gemini_api_key', key.trim());
}

// ─── Pipeline ────────────────────────────────────────────────────────────────

async function runPipeline(topic, apiKey) {
  setLaunchButton(false);
  resetAllAgents();
  hideFinalReport();

  try {
    // Stage 1 — Planner
    showToast('🧭 Planner Agent started…', 'info');
    const outline = await runPlanner(topic, apiKey);
    showToast('✅ Planner complete!', 'success');

    // Stage 2 — Researcher
    showToast('🔬 Researcher Agent started…', 'info');
    const notes = await runResearcher(outline, apiKey);
    showToast('✅ Researcher complete!', 'success');

    // Stage 3 — Writer
    showToast('✍️ Writer Agent started…', 'info');
    const draft = await runWriter(notes, apiKey);
    showToast('✅ Writer complete!', 'success');

    // Stage 4 — Reviewer
    showToast('🔍 Reviewer Agent started…', 'info');
    const review = await runReviewer(draft, apiKey);
    showToast('✅ Reviewer complete!', 'success');

    // Assemble final report
    const finalReport = assembleFinalReport(topic, outline, draft, review);
    showFinalReport(finalReport);
    showToast('🎉 Pipeline complete! Report ready.', 'success');

    // Store for download
    window._finalReport = finalReport;
    window._draftReport = draft;

  } catch (err) {
    showToast(`❌ Pipeline failed: ${err.message}`, 'error');
    console.error('[Pipeline Error]', err);
  } finally {
    setLaunchButton(true);
  }
}

function assembleFinalReport(topic, outline, draft, review) {
  return `# 📄 Research Report: ${topic}

---

## 🗂️ Research Outline (Planner Agent)

${outline}

---

## 📝 Full Research Article (Writer Agent)

${draft}

---

## 🔍 Peer Review (Reviewer Agent)

${review}

---
*Generated by Multi-Agent Research Assistant powered by Google Gemini 2.0 Flash*
`;
}

// ─── Event Listeners ─────────────────────────────────────────────────────────

document.addEventListener('DOMContentLoaded', () => {
  // Restore saved API key
  const keyInput = document.getElementById('input-api-key');
  if (keyInput) {
    keyInput.value = getApiKey();
    keyInput.addEventListener('change', () => saveApiKey(keyInput.value));
    keyInput.addEventListener('blur',   () => saveApiKey(keyInput.value));
  }

  // Toggle API key visibility
  const toggleBtn = document.getElementById('btn-toggle-key');
  if (toggleBtn && keyInput) {
    toggleBtn.addEventListener('click', () => {
      const isPassword = keyInput.type === 'password';
      keyInput.type = isPassword ? 'text' : 'password';
      toggleBtn.textContent = isPassword ? '🙈' : '👁️';
    });
  }

  // Launch button
  const launchBtn = document.getElementById('btn-launch');
  if (launchBtn) {
    launchBtn.addEventListener('click', () => {
      const topic  = document.getElementById('input-topic')?.value?.trim();
      const apiKey = document.getElementById('input-api-key')?.value?.trim();

      if (!topic) {
        showToast('⚠️ Please enter a research topic.', 'warning');
        return;
      }
      if (!apiKey) {
        showToast('⚠️ Please enter your Gemini API key.', 'warning');
        return;
      }

      saveApiKey(apiKey);
      runPipeline(topic, apiKey);
    });
  }

  // Download full report
  const downloadBtn = document.getElementById('btn-download');
  if (downloadBtn) {
    downloadBtn.addEventListener('click', () => {
      const report = window._finalReport;
      if (!report) return;
      const topic = document.getElementById('input-topic')?.value?.trim() || 'research-report';
      const slug  = topic.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
      downloadMarkdown(report, `${slug}-report.md`);
    });
  }

  // Download article only
  const downloadArticleBtn = document.getElementById('btn-download-article');
  if (downloadArticleBtn) {
    downloadArticleBtn.addEventListener('click', () => {
      const draft = window._draftReport;
      if (!draft) return;
      const topic = document.getElementById('input-topic')?.value?.trim() || 'article';
      const slug  = topic.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
      downloadMarkdown(draft, `${slug}-article.md`);
    });
  }

  // Copy report to clipboard
  const copyBtn = document.getElementById('btn-copy');
  if (copyBtn) {
    copyBtn.addEventListener('click', async () => {
      const report = window._finalReport;
      if (!report) return;
      try {
        await navigator.clipboard.writeText(report);
        showToast('📋 Report copied to clipboard!', 'success');
      } catch {
        showToast('❌ Copy failed. Please copy manually.', 'error');
      }
    });
  }
});

function downloadMarkdown(content, filename) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
  showToast(`📥 Downloading ${filename}`, 'success');
}
